version: "3.8"


services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:${POSTGRES_PORT}"
    # HEALTH CHECK

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST:${POSTGRES_HOST}
      - DB_PORT:${POSTGRES_PORT}
      - DB_USER:${POSTGRES_USER}
      - DB_PASSWORD:${POSTGRES_PASSWORD}
      - DB_NAME:${POSTGRES_DB}
    depends_on:
      - db
